# Medium - Find the Difference
# You are given two strings s and t. String t is generated by randomly shuffling
# string s and then adding one more letter at a random position. Return the letter that was added to t.
# Examples
# find_the_difference("abcd", "abcde") ➞ "e"
# find_the_difference("", "y") ➞ "y"
# find_the_difference("ae", "aea") ➞ "a"

def find_the_difference(s, t)
  s_arr = s.split('')
  t_arr = t.split('')

  t_arr.select.each_with_index { |item, index|
    s_arr[index] != item
  }.join('')
end

puts find_the_difference("abcd", "abcde") == "e"
puts find_the_difference("", "y") == "y"
puts find_the_difference("ae", "aea") == "a"